export XDG_CONFIG_HOME="$HOME/.config"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_SOFTWARE_DIR="$HOME/software"
